### ISSUE TITLE
转换pdf时报错，服务器抛出异常

### ISSUE THREAD

**Issue by zndevel** [tal-tech/h5-transfer-pdf#4]
我按照文档中的步骤进行安装部署，成功了，但是对文档进行转换时报错：
请求JSON：
{
    "url": "https://www.qq.com/",
    "outputType": "PDF",
    "fileName": "test1"
}

返回响应：
{
    "content": null,
    "status": false,
    "message": "render PDF fail"
}

服务器上抛出异常：
[DEBUG] 2020-10-02 21:14:08.650 [http-nio-8084-exec-5] com.tal.generate.pdf.pdf.GenerateCommon[readProcessOnError][108] - process exec result: ["module.js:549","    throw err;","    ^","","Error: Cannot find module \u0027/data/h5-transfer-pdf-1.0.0/file:/data/h5-transfer-pdf-1.0.0/lib/log4j-api-2.13.3.jar!/META-INF/versions/9/static/render-pdf.js\u0027","    at Function.Module._resolveFilename (module.js:547:15)","    at Function.Module._load (module.js:474:25)","    at Function.Module.runMain (module.js:693:10)","    at startup (bootstrap_node.js:188:16)","    at bootstrap_node.js:609:3"]
[ERROR] 2020-10-02 21:14:08.651 [http-nio-8084-exec-5] c.t.generate.pdf.service.GeneratePdfCommandService[generatePdf][51] - render PDF fail

**Comment by zhaiyarong** [comment]
您好，请提供一下信息： 1.  是通过哪种方式启动的，源码还是jar方式？ 2. 是否已经安装相关依赖，并全部安装成功  3.请提供一下js产生的日志信息（debugxxxx-xx-xx.log）
