### ISSUE TITLE
关于执行报错的问题

### ISSUE THREAD

**Issue by iceMr** [tal-tech/h5-transfer-pdf#8]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "node": error=11, Resource temporarily unavailable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.tal.generate.pdf.pdf.RunProcessFunction.run(RunProcessFunction.java:34)
        at com.tal.generate.pdf.pdf.GenerateCommon.run(GenerateCommon.java:164)
        at com.tal.generate.pdf.pdf.PdfGenerate.run(PdfGenerate.java:18)
        at com.tal.generate.pdf.service.GeneratePdfCommandService.renderPdf(GeneratePdfCommandService.java:68)
        at com.tal.generate.pdf.service.GeneratePdfCommandService.generatePdf(GeneratePdfCommandService.java:49)
        ... 61 common frames omitted
Caused by: java.io.IOException: error=11, Resource temporarily unavailable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 66 common frames omitted
[ERROR] 2024-09-19 08:16:29.167 [http-nio-8077-exec-5] c.t.generate.pdf.service.GeneratePdfCommandService[generatePdf][51] - render PDF fail 
java.io.IOException: Timed out read process's input stream to finish
        at com.tal.generate.pdf.pdf.GenerateCommon.readProcessOnError(GenerateCommon.java:112)
        at com.tal.generate.pdf.pdf.GenerateCommon.readProcessOnError(GenerateCommon.jav

有些说是因为 linux 资源文件打开设置数量问题,修改之后依然会出现如下问题 . 这个是什么原因造成的 ?

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
